# Generated by Django 5.0.3 on 2025-02-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerenciador_de_clientes', '0001_initial'),
        ('gerenciador_de_funcionarios', '0001_initial'),
        ('gerenciador_de_motoboys', '0001_initial'),
        ('gerenciador_de_produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_clientes.cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='gerenciador_de_funcionarios.funcionario')),
                ('motoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_motoboys.motoboy')),
                ('produtos', models.ManyToManyField(to='gerenciador_de_produtos.produto')),
            ],
        ),
    ]
