# Generated by Django 5.0.3 on 2024-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_pedidos', '0001_initial'),
        ('gerenciador_de_produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='gerenciador_de_produtos.produto'),
        ),
    ]
