# Generated by Django 5.0.3 on 2024-04-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_clientes', '0002_cliente_delete_gerenciadordeclientes'),
        ('gerenciador_de_pedidos', '0002_remove_pedido_total_remove_pedido_produtos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_clientes.cliente'),
        ),
    ]
