# Generated by Django 5.0.3 on 2024-04-09 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_funcionarios', '0001_initial'),
        ('gerenciador_de_pedidos', '0003_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='gerenciador_de_funcionarios.funcionario'),
        ),
    ]
