# Generated by Django 5.0.3 on 2024-04-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_motoboys', '0003_rename_cadastrante_motoboy_funcionario'),
        ('gerenciador_de_pedidos', '0004_pedido_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motoboy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador_de_motoboys.motoboy'),
        ),
    ]
