# Generated by Django 5.0.3 on 2024-04-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_pedidos', '0005_pedido_motoboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20),
        ),
    ]
