# Generated by Django 5.0.3 on 2024-04-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_pedidos', '0006_pedido_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='data_hora',
            new_name='data_hora_inicio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_hora_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
