# Generated by Django 5.0.3 on 2024-04-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
