# Generated by Django 5.0.3 on 2024-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_clientes', '0002_cliente_delete_gerenciadordeclientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco',
            new_name='rua',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(default='sem dados', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
