# Generated by Django 5.0.3 on 2024-09-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_clientes', '0003_rename_endereco_cliente_rua_cliente_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='sem bairro', max_length=200),
            preserve_default=False,
        ),
    ]
