# Generated by Django 5.0.3 on 2024-10-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_clientes', '0007_alter_cliente_numero'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('nome', 'telefone', 'cep', 'logradouro', 'numero', 'complemento', 'bairro'), name='unique_cliente'),
        ),
    ]
