# Generated by Django 5.0.3 on 2025-02-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerenciador_de_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=20)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_funcionarios.funcionario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='motoboy',
            constraint=models.UniqueConstraint(fields=('nome', 'telefone', 'placa'), name='unique_motoboy'),
        ),
    ]
