# Generated by Django 4.2.11 on 2024-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motoboy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=30)),
                ("placa", models.CharField(max_length=20)),
            ],
        ),
    ]
