# Generated by Django 5.0.3 on 2024-03-30 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_funcionarios', '0001_initial'),
        ('gerenciador_de_motoboys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='cadastrante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gerenciador_de_funcionarios.funcionario'),
        ),
    ]
