# Generated by Django 5.1.6 on 2025-02-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_motoboys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='senha',
            field=models.CharField(blank=True, default='default_senha', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motoboy',
            name='usuario',
            field=models.CharField(blank=True, default='default_usuario', max_length=100, null=True, unique=True),
        ),
    ]
