# Generated by Django 5.0.3 on 2024-03-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_motoboys', '0002_motoboy_cadastrante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoboy',
            old_name='cadastrante',
            new_name='funcionario',
        ),
    ]
