# Generated by Django 5.0.3 on 2024-10-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_de_funcionarios', '0003_alter_funcionario_cpf_alter_funcionario_email'),
        ('gerenciador_de_motoboys', '0003_rename_cadastrante_motoboy_funcionario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='motoboy',
            constraint=models.UniqueConstraint(fields=('nome', 'telefone', 'placa'), name='unique_motoboy'),
        ),
    ]
